// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7wwWcz7u7nApTrq-deNYD7zeN7TXrT0',
    appId: '1:439001214909:web:5cdde440de0452b042ecd4',
    messagingSenderId: '439001214909',
    projectId: 'fluttertypescriptcourse',
    authDomain: 'fluttertypescriptcourse.firebaseapp.com',
    storageBucket: 'fluttertypescriptcourse.appspot.com',
    measurementId: 'G-6EZY025H7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zXsmEKf_MxFvuKG5qBSI6U2mjaoJPzg',
    appId: '1:439001214909:android:d75e1c1acbb66eec42ecd4',
    messagingSenderId: '439001214909',
    projectId: 'fluttertypescriptcourse',
    storageBucket: 'fluttertypescriptcourse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpwYPKumFM3g8b7NcYuxfgNmfIOM8qWY',
    appId: '1:439001214909:ios:d9b80954c258863242ecd4',
    messagingSenderId: '439001214909',
    projectId: 'fluttertypescriptcourse',
    storageBucket: 'fluttertypescriptcourse.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpwYPKumFM3g8b7NcYuxfgNmfIOM8qWY',
    appId: '1:439001214909:ios:d50f0afccb735e2942ecd4',
    messagingSenderId: '439001214909',
    projectId: 'fluttertypescriptcourse',
    storageBucket: 'fluttertypescriptcourse.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp.RunnerTests',
  );
}
